expression: Maybe.map f (Maybe.map g fx)
steps:
  - code: |
      Maybe.map f (Maybe.map g Nothing)
    explanation: "Definition von `fx`"
  - code: |
      Maybe.map f (case Nothing of
                       Nothing ->
                           Nothing

                       Just value ->
                           Just (g value))
    explanation: "Definition von `Maybe.map`"
  - code: |
      Maybe.map f Nothing
    explanation: "Auswertung des `case`-Ausdrucks"
  - code: |
      case Nothing of
          Nothing ->
              Nothing

              Just value ->
                  Just (f value)
    explanation: "Definition von `Maybe.map`"
  - code: |
      Nothing
    explanation: "Auswertung des `case`-Ausdrucks"
